name: Data Preprocessing Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'preprocessing/**'
  workflow_dispatch:

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy

    - name: Run Preprocessing Script
      run: |
        python preprocessing/porter-delivery-time-estimation_preprocessing/automate_Dika-Ramadani.py

    - name: Upload Preprocessed Artifact
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-dataset
        path: preprocessing/porter-delivery-time-estimation_preprocessing/porter_delivery_preprocessed.csv